#定义CI步骤：编译和部署
stages:
    - sonar
    - build
    - deploy
    - review

sonar_job:
    stage: sonar
    script:
        - /opt/sonar-scanner-cli/bin/sonar-scanner -D:sonar.pullrequest.key=${CI_MERGE_REQUEST_IID}$ -D:sonar.pullrequest.branch=${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}$ -D:sonar.pullrequest.base=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}$  -D:sonar.ws.timeout=30 -D:sonar.links.homepage=${CI_PROJECT_URL}$ -D:sonar.sourceEncoding=UTF-8 -D:sonar.gitlab.ref_name=${CI_COMMIT_REF_NAME}$ -D:sonar.gitlab.commit_sha=${CI_COMMIT_SHA}$ -D:sonar.gitlab.project_id=${CI_PROJECT_PATH}$ -D:sonar.pullrequest.gitlab.repositorySlug=${CI_PROJECT_ID}$
    tags:
        - Vue_Build_Linux
    only:
        - merge_requests

#代码编译，所有提交均触发
build_job:
    stage: build
    variables:
        #以克隆的模式获取当前分支代码
        GIT_STRATEGY: clone
        #编译后安装包名称
        PACKAGE_NAME: srm-web
        #编译后程序所在目录
        PROGRAM_DIR: nginx-srm-web
    script:
        #获取当前目录
        - cur_dir=`pwd`
        - echo $cur_dir
        #获取alpha版本号，如果不传入则为空
        - softversion="$version"
        #下载nginx包，解压
        - curl http://storage.rdapp.com/download/dXBsb2Fkcy9jb21tb24vc29mdHdhcmUvbmdpbngtMV8xNF8yLnppcA==/h/72769d17c07d8d696a81d2b351c737fb -o $PROGRAM_DIR.zip
        - unzip -d $PROGRAM_DIR $PROGRAM_DIR.zip
        #生成verion.json文件
        - sh CICDFiles/version.sh ${CI_PIPELINE_ID} ${CI_COMMIT_REF_NAME}
        #如果传入的版本号不为空，则替换version.json中的版本号
        - if [ "$softversion" != "" ];then echo "input version:$softversion";sed -i -r "s/(.*Tag_version.*:).*/\1\ \"${softversion}\.${CI_PIPELINE_ID}\",/g" version.json;fi
        #复制version.json到编译产物的文件夹根目录，PROGRAM_DIR
        - cp -f version.json $PROGRAM_DIR/
        #转化README.md为版本说明.pdf
        - if [ -f README.md ];then pandoc --pdf-engine=xelatex --template=/usr/share/scripts/template.latex README.md -o README.pdf  && mv README.pdf $PROGRAM_DIR/;fi
        - npm ci -f
        #编译vue源码
        - npm run build
        - /bin/cp -rf dist/* $PROGRAM_DIR/web/

        #下载Google的Office预览扩展程序
        - curl -o $PROGRAM_DIR/web/Google-OfficePreview-[149_93_109].zip https://package.genew.com/download/dXBsb2Fkcy9jb21tb24vc29mdHdhcmUvc29mdHBob25lL0dvb2dsZS1PZmZpY2VQcmV2aWV3LSU1QjE0OV85M18xMDklNUQuemlw/h/0621f7aa59bd65dca38567daa172630b

        - /bin/cp -rf CICDFiles/* $PROGRAM_DIR/
        - if [ -f public/config-template.json ];then /bin/cp -rf public/config-template.json  $PROGRAM_DIR/web/;else echo "config-template.json is not existed...";fi
        - rm -rf $PROGRAM_DIR/version.sh
        - cp $PROGRAM_DIR/nginx.conf $PROGRAM_DIR/conf/
        #切换到编译产物的文件夹打包成zip包，PROGRAM_DIR,替换为编译产物的目录，zip包名替换为服务名
        - cd $PROGRAM_DIR
        - zip -r $cur_dir/$PACKAGE_NAME.zip ./*

    allow_failure: false
    artifacts:
        name: '$SERVICE_NAME-$CI_COMMIT_REF_NAME'
        #需要下载的文件或文件夹，可写正则和多个
        paths:
            - srm-web.zip
            - version.json
        expire_in: 24h
    tags:
        #选择运行的gitrunner的tag，选择具有编译相关语言代码能力的gitrunner
        #- Vue_Linux_Node
        - Web_Node18

#部署新包到dev环境
deploy_job:
    stage: deploy
    variables:
        #不重新获取代码，使用build_job中的文件
        GIT_STRATEGY: none
        PROJECT_NAME: srm-web
    script:
        #程序的服务名称
        - if [ -n "$SpecifyName" ] ; then SERVICE_NAME="srm-web-$SpecifyName"; mv ${PROJECT_NAME}.zip ${SERVICE_NAME}.zip ;else SERVICE_NAME="srm-web" ; fi
        #重命名安装包名称
        - echo ${SERVICE_NAME}.zip
        #停止服务
        - curl -X PATCH "http://127.0.0.1:6619/api/WatchDogs/${SERVICE_NAME}/control-unit/stop" -H "accept:application/json" -v
        #等待服务停止，默认等待5秒
        - ping -n 5 127.0.0.1 || sleep 5
        #上传安装包
        - curl "http://127.0.0.1:6619/api/Deploy/UploadLargeFile" -F "file=@./${SERVICE_NAME}.zip" -v
        #等待服务安装，默认等待30秒
        - ping -n 30 127.0.0.1 || sleep 30
        #启动服务
        - curl -X PATCH "http://127.0.0.1:6619/api/WatchDogs/${SERVICE_NAME}/control-unit/start" -H "accept:application/json" -v
    tags:
        - SRM_WEB_DEV
    only:
        - dev_3.X
    environment:
        name: $PROJECT_NAME_dev_env

#推送到部署包到网盘，仅在打了tag或在gitlab web运行流水线时触发
publish_job:
    stage: deploy
    variables:
        #不重新获取代码，使用build_job中的文件
        GIT_STRATEGY: none
        #编译后安装包名称
        PACKAGE_NAME: srm-web
    script:
        #程序的服务名称
        - if [ -n "$SpecifyName" ] ; then SERVICE_NAME="$PACKAGE_NAME-$SpecifyName";mv ${PACKAGE_NAME}.zip ${SERVICE_NAME}.zip; else SERVICE_NAME="$PACKAGE_NAME" ; fi
        - echo $SERVICE_NAME
        - echo $SpecifyName
        #获取传入的版本号
        - softversion="$version"
        #获取version.json的版本号
        - v=`grep "Tag_version" version.json|awk -F "\"" '{print $4}'`
        #如果传入版本号为空，则版本为version.json的版本号，否则上传目录为alpha，版本号为传入版本-alpha
        - if [ "$softversion" == "" ];then softversion="$v";else publishdir="alpha/$project" && softversion="$v";fi
        #如果手动版本号和TAG均为空，则根据分支名切割project
        - if [ "$CI_COMMIT_TAG$version" == "" ];then publishdir="alpha/000项目/$(echo $CI_COMMIT_REF_NAME|sed -r  's/^[0-9]+.[0-9]+.[0-9]+-//')";fi
        - echo "publishdir:$publishdir"
        #如果存在同名版本包，先删除
        - if [ -f ${SERVICE_NAME}-V${softversion}.zip ];then rm -rf ${SERVICE_NAME}-V${softversion}.zip;fi
        #重命名服务包名为带版本号报名
        - echo  ${SERVICE_NAME}.zip   ${SERVICE_NAME}-V${softversion}.zip
        - mv ${SERVICE_NAME}.zip     ${SERVICE_NAME}-V${softversion}.zip
        #创建目录
        - ssh root@storage.rdapp.com  "mkdir -p /opt/lampp/htdocs/apps/vfm/uploads/common/Packages/$publishdir"
        #推送软件包到网盘指定目录
        - scp ${SERVICE_NAME}-V${softversion}.zip root@storage.rdapp.com:/opt/lampp/htdocs/apps/vfm/uploads/common/Packages/$publishdir
        #修改软件包属组
        - ssh root@storage.rdapp.com  "chown -R daemon:daemon /opt/lampp/htdocs/apps/vfm/uploads/common/Packages/$publishdir"
    tags:
        - Vue_Build_Linux
    only:
        - tags
        - web

review_job:
    when: manual
    stage: review
    only:
        - merge_requests
    before_script:
        - git submodule update --init --recursive --remote
    script:
        - ai-review run
    variables:
        GIT_DEPTH: 0
        VCS__PIPELINE__PROJECT_ID: "$CI_PROJECT_ID"
        VCS__PIPELINE__MERGE_REQUEST_ID: "$CI_MERGE_REQUEST_IID"
        AI_REVIEW_CONFIG_FILE_YAML: "./ai-review/.ai-review.yaml"
    allow_failure: true
    tags:
        - ai-review-docker

